baseURL = 'http://iss-namespaces.pages.dev/'
languageCode = 'en-us'
title = 'To Docker and Beyond!'
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "white"
